"""Add game_user Association Table

Revision ID: 03b80ab32f47
Revises: 95a4ac6e9242
Create Date: 2023-09-06 17:12:12.218548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b80ab32f47'
down_revision = '95a4ac6e9242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
